spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
  ai:
    ollama:
      ## 默认地址无需配置
      base-url: http://localhost:11434
      chat:
        model: gemma:2b
#    openai:
#      api-key: <ApiKey>
